package cloud.delaye.backend.entities;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Map;

/**
 * Transfer object for Event
 * @author Valentin Delaye (valentin.delaye@novaccess.ch)
 */
@JsonPropertyOrder(EventTo.ID)
public class EventTo {
	
	//<editor-fold defaultstate="collapsed" desc="Constants">
	public static final String ID = "id";
	//</editor-fold>
	
	/**
	 * Event ID (generated by server)
	 */
	@JsonProperty(ID)
	public Long id;
	
    @JsonIgnore
    private Map<String, Object> map;	
	
    @JsonAnyGetter
    public Map<String, Object> map() {
        return map;
    }

    @JsonAnySetter
    public Object put(String key, Object value) {
        return map.put(key, value);
    }	

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@JsonIgnore
	public Map<String, Object> getMap() {
		return map;
	}

	@JsonIgnore
	public void setMap(Map<String, Object> map) {
		this.map = map;
	}
	
}
